version: '3.7'

services:
  news_db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  news_web:
    build: .
    command: bash -c "python /newsproject/manage.py migrate --noinput &&
             python /newsproject/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/newsproject
    ports:
       - 8000:8000
    depends_on:
      - news_db

volumes:
      postgres_data: