# Generated by Django 3.1.2 on 2020-10-27 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201027_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default='google.com', max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 9, 5, 10, 278373)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 9, 5, 10, 277679)),
        ),
    ]
