# Generated by Django 3.1.2 on 2020-10-27 18:03

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_auto_20201027_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvote',
            old_name='user',
            new_name='voted',
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 18, 3, 29, 324839)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 18, 3, 29, 324297)),
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('voted', 'post')},
        ),
    ]
